export const tasks = [
    {
        "size": 1,
        "total": 1,
        "start": 0,
        "data": [
            {
                "id": "4768b8f9-cf07-11ee-8b97-28d0eada1d8b",
                "name": "initial form",
                "description": null,
                "category": null,
                "assignee": {
                    "id": "admin",
                    "firstName": "Test",
                    "lastName": "Administrator",
                    "email": "admin@flowable.org",
                    "fullName": "Test Administrator",
                    "groups": [],
                    "privileges": []
                },
                "created": "2024-02-19T09:14:26.483+0000",
                "dueDate": null,
                "endDate": null,
                "duration": null,
                "priority": 50,
                "processInstanceId": "476891e2-cf07-11ee-8b97-28d0eada1d8b",
                "processInstanceName": null,
                "processDefinitionId": "myProcessWithForm1:8:cc314edf-cc99-11ee-9b2d-28d0eada1d8b",
                "processDefinitionName": "myProcessWithForm1",
                "processDefinitionDescription": null,
                "processDefinitionKey": "myProcessWithForm1",
                "processDefinitionCategory": "http://www.flowable.org/processdef",
                "processDefinitionVersion": 8,
                "processDefinitionDeploymentId": "cc1ae0ac-cc99-11ee-9b2d-28d0eada1d8b",
                "scopeId": null,
                "scopeType": null,
                "caseInstanceName": null,
                "scopeDefinitionId": null,
                "caseDefinitionName": null,
                "caseDefinitionDescription": null,
                "caseDefinitionKey": null,
                "caseDefinitionCategory": null,
                "caseDefinitionVersion": 0,
                "caseDefinitionDeploymentId": null,
                "parentTaskId": null,
                "parentTaskName": null,
                "formKey": "LoanApplication",
                "processInstanceStartUserId": null,
                "initiatorCanCompleteTask": false,
                "memberOfCandidateUsers": false,
                "memberOfCandidateGroup": false
            }
        ]
    },
    {
        "size": 1,
        "total": 1,
        "start": 0,
        "data": [
            {
                "id": "029a20f3-cf07-11ee-8b97-28d0eada1d8b",
                "name": "LLb application",
                "description": null,
                "category": null,
                "assignee": {
                    "id": "admin",
                    "firstName": "Test",
                    "lastName": "Administrator",
                    "email": "admin@flowable.org",
                    "fullName": "Test Administrator",
                    "groups": [],
                    "privileges": []
                },
                "created": "2024-02-19T09:12:31.044+0000",
                "dueDate": null,
                "endDate": null,
                "duration": null,
                "priority": 50,
                "processInstanceId": "0299d2cc-cf07-11ee-8b97-28d0eada1d8b",
                "processInstanceName": null,
                "processDefinitionId": "LLBnew:6:10b51b9e-cf03-11ee-8b97-28d0eada1d8b",
                "processDefinitionName": "LLBnew",
                "processDefinitionDescription": null,
                "processDefinitionKey": "LLBnew",
                "processDefinitionCategory": "http://www.flowable.org/processdef",
                "processDefinitionVersion": 6,
                "processDefinitionDeploymentId": "1094743b-cf03-11ee-8b97-28d0eada1d8b",
                "scopeId": null,
                "scopeType": null,
                "caseInstanceName": null,
                "scopeDefinitionId": null,
                "caseDefinitionName": null,
                "caseDefinitionDescription": null,
                "caseDefinitionKey": null,
                "caseDefinitionCategory": null,
                "caseDefinitionVersion": 0,
                "caseDefinitionDeploymentId": null,
                "parentTaskId": null,
                "parentTaskName": null,
                "formKey": "UserInfo",
                "processInstanceStartUserId": null,
                "initiatorCanCompleteTask": false,
                "memberOfCandidateUsers": false,
                "memberOfCandidateGroup": false
            }
        ]
    }
]